logging.level.root: INFO
server.port: 8761
registry.shutdown-old: true
ribbon.eureka.enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    enableSelfPreservation: false