logging.level.root: INFO
server.port: 8761
ribbon:
  eureka.enabled: false
  ReadTimeout: 120000
  ConnectTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
hystrix.command.default.execution.timeout.enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    enableSelfPreservation: false