logging.level.root: INFO
server.port: 8761
spring.application.name: router
endpoints:
  routes.sensitive: false
ribbon:
  eureka.enabled: false
  ReadTimeout: 120000
  ConnectTimeout: 5000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
hystrix.command.default.execution.timeout.enabled: false
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka
  server:
    enableSelfPreservation: false